### PR TITLE
Handle backspace on first character of all-space line correctly

### LINKED ISSUE #3915: At beginning of line with all spaces, backspace causes error
**Describe the bug**
See issue title

**To Reproduce**

1.  On a line with only space characters, go to first column
2.  Enter insert mode with `i`
3.  Press `<BS>`
4.  Observe the error, nothing is deleted

**Expected behavior**
No error; newline is deleted

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.2
- VSCode version: 1.36.1
- OS: Windows 10

### PR DESCRIPTION
**Pull request by J-Fields**
**What this PR does / why we need it**:
On an all-spaces line, you press backspace in insert mode, it'll cause an error. Now this corner case is accounted for.

**Which issue(s) this PR fixes**
Fixes #3915

### CODE REVIEW

File: src/actions/commands/insert.ts [hunk 1]
```diff
@@ -249,9 +249,15 @@ export class CommandInsertInInsertMode extends BaseCommand {
           range: new Range(selection.start as Position, selection.end as Position),
         });
       } else {
-        if (line.length > 0 && line.match(/^ +$/) && configuration.expandtab) {
-          // If the line is empty except whitespace, backspace should return to
-          // the next lowest level of indentation.
+        if (
+          position.character > 0 &&
+          line.length > 0 &&
+          line.match(/^ +$/) &&
```
Comment (jpoon) [inline src/actions/commands/insert.ts]: nit: replace the literal ` ` with `\s` in regex.
