### PR TITLE
fix #690 and other toggle case issues

### LINKED ISSUE #690: ~ to change case followed by . to repeat command unexpectedly repeats previous action, not ~
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Position cursor on text
Type tilde to invert case of character under cursor (~)
Navigate to another line with mouse
Type '.' to repeat last action (~)

### What did you expect to happen?
I expected '.' to repeat the ~ action and change the case of the character under the cursor

### What happened instead?
The entire line under the cursor was deleted as this repeated an earlier 'dd', not the ~ action.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

### PR DESCRIPTION
**Pull request by xconverge**
Toggle case wasn't toggling interWoVen cases...

Also made it repeatable with dot and <num> correctly

### CODE REVIEW

File: src/actions/actions.ts [hunk 1]
```diff
@@ -3537,17 +3537,52 @@ class ToggleCaseOperator extends BaseOperator {
...
+  public keys = ["~"];
+  public modes = [ModeName.VisualBlock];
+
+  public async run(vimState: VimState, start: Position, end: Position): Promise<VimState> {
+    for (const { start, end } of Position.IterateLine(vimState)) {
+      const range = new vscode.Range(start, end);
+      const text = TextEditor.getText(range);
+
+      let newText = "";
+      for (var i = 0; i < text.length; i++) {
```
Comment (johnfn) [inline src/actions/actions.ts]: Can you refactor out this duplicated code?

Comment (xconverge) [inline src/actions/actions.ts]: Yea I was waiting for this comment, I figured that this was better than polluting the other one with VisualBlock specific stuff.

Where would a function like this to DRY it up go?

File: src/actions/actions.ts [hunk 2]
```diff
@@ -3537,20 +3537,55 @@ class ToggleCaseOperator extends BaseOperator {
 
   public async run(vimState: VimState, start: Position, end: Position): Promise<VimState> {
     const range = new vscode.Range(start, new Position(end.line, end.character + 1));
```
Comment (jpoon) [inline src/actions/actions.ts]: Can you also change this to: `new vscode.Range(start, end.getRight());`.

Probably doesn't matter but I'd sleep better at night with the position checking.

File: src/actions/actions.ts [hunk 3]
```diff
@@ -3537,20 +3537,55 @@ class ToggleCaseOperator extends BaseOperator {
...
-    if (toggled === char) {
-      // Try upper-case
-      toggled = char.toLocaleUpperCase();
+    const text = TextEditor.getText(range);
+
+    let newText = "";
+    for (var i = 0; i < text.length; i++) {
+      var char = text[i];
+      // Try lower-case
+      let toggled = char.toLocaleLowerCase();
```
Comment (jpoon) [inline src/actions/actions.ts]: Instead of checking whether it was toggled, how do you guys feel about an ASCII hack :)

1) Check if the char is A-Za-z
2) XOR the char code with the ASCII for space (32). `String.fromCharCode(char.charCodeAt(0) ^ 32)`

**Comment by jpoon** [comment]
Pending @johnfn's comment. LGTM.

File: src/actions/actions.ts (hunk 1 above)
Comment (johnfn) [inline src/actions/actions.ts]: Haha, yeah, you know it had to happen. Maybe in a utilities file somewhere? Or if you can't find/dont want to make one, then a static method on a class can work.

Comment (jpoon) [inline src/actions/actions.ts]: +1 static method in a separate class

File: src/actions/actions.ts (hunk 2 above)
Comment (xconverge) [inline src/actions/actions.ts]: Will do, insomnia is no fun

**Comment by xconverge** [comment]
Should be good to go

**Comment by jpoon** [comment]
@xconverge once you merge latest from `master`, I can get this in.
