### PR TITLE
Fix wrong return in ModeHandlerMap.get

### LINKED ISSUE #4479: <c-o>/<c-t> jump back to wrong location after 'gd'
**Describe the bug**
Pressing <C-o> after 'gd' goes to a different file and not back to the previous location.

Re-reporting #3277 since this bug has not been re-introduced (I'm guessing after the 1s sleep was removed)

**To Reproduce**
Press 'gd'
Press <C-o>
Now in wrong location

**Expected behavior**
Going to the previous location

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: macOS 10.14.6

**Additional context**

### PR DESCRIPTION
**Pull request by fatanugraha**
Hello, in my setup, this resolves #4479, #3277

From what i can observe, here's what i found to arrive to this conclusion:
- on `vscode.window.onDidChangeActiveTextEditor` i always get `lastClosedModeHandler = undefined` despite that the current file is exists on `ModeHandlerMap`
- due to `lastClosedModeHandler = undefined` jumping from current file doesn't push it to the jump stack

### CODE REVIEW

File: src/editorIdentity.ts [hunk 1]
```diff
@@ -13,11 +13,15 @@ export class EditorIdentity {
   /**
    * For use in tests
    */
-  public static createRandomEditorIdentity(): EditorIdentity {
+  public static createRandomEditorIdentity(
```
Comment (J-Fields) [inline src/editorIdentity.ts]: Why not just call `new EditorIdentity` in the test yourself? Seems weird to call `createRandom` and then override the randomness

**Comment by J-Fields** [comment]
Nice catch, thanks for the PR! I'll take a closer look later but this seems reasonable and does fix the issue, I think.

File: src/editorIdentity.ts (hunk 1 above)
Comment (fatanugraha) [reply src/editorIdentity.ts]: the constructor for `EditorIdentity` is marked as `private`. Should i made it `public` or create a new method for it?

Comment (J-Fields) [reply src/editorIdentity.ts]: Just make it public; you're exposing essentially the same API but less clearly by adding a parameter to the create random function.

Comment (fatanugraha) [reply src/editorIdentity.ts]: Sure, i also removed the `createRandomEditorIdentity` method.

**Comment by jpoon** [comment]
Thanks for the fix!
