### PR TITLE
Fixes #1256 and #394: Fixes delete key and adds functionality

### LINKED ISSUE #1256: Inconsistencies with visual mode deletion
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. While in normal mode, use mouse to select any amount of text, triggering visual mode selection.
2. Press `delete` key (not backspace).

### What did you expect to happen?

I'd expect the same as if I had used `d` to delete the text after selecting it:

Selected text is deleted, and editor returns to normal mode.
Cursor is displayed as block cursor, indicating normal mode.

### What happened instead?

Selected text is deleted, and editor remains in visual mode.
Cursor is bar cursor, indicating visual mode.

### What did you do?

1. Select text as before.
2. a) Press `delete` or `d`, then press a vertical movement key: `arrow up`, `arrow down`, `j`, or `k`.
    b) Press `delete`, then press a horizontal movement key. (Horizontal movement works as expected for deletion with `d`.)

### What did you expect to happen?

Moving the cursor originates movement from its currently displayed location.

### What happened instead?

Movement occurs relative to the character position of what was the end of the selection before deleting it. This leads to a horizontal jump when moving the cursor vertically (after either `delete` or `d`), or a sudden visual mode selection when moving the cursor horizontally (only after `delete`).

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: Ubuntu 16.10

### PR DESCRIPTION
**Pull request by Chillee**
Otherwise, this PR fixes the first part of #1256 through just adding more key capturing, and fixes the second part by setting desiredColumn in visual mode.

### CODE REVIEW

File: src/actions/actions.ts [hunk 1]
```diff
@@ -2154,7 +2151,7 @@ export class ShiftYankOperatorVisual extends BaseOperator {
 
 @RegisterAction
 export class DeleteOperatorXVisual extends BaseOperator {
```
Comment (Chillee) [inline src/actions/actions.ts]: Decided not to change the name because <Del> is just a synonym in visual mode. Come to think of it, can't we combine `d` in visual mode with this as well?

File: package.json [hunk 2]
```diff
@@ -117,7 +117,7 @@
       {
         "key": "Delete",
         "command": "extension.vim_delete",
-        "when": "editorTextFocus && vim.active && vim.mode == 'Normal' && !inDebugRepl"
+        "when": "editorTextFocus && vim.active && !inDebugRepl"
```
Comment (xconverge) [inline package.json]: does delete work in insert mode now?

Comment (Chillee) [inline package.json]: I think it still passes through to VSCode since none of our actions capture `<Del>` in InsertMode.

**Comment by rebornix** [comment]
@Chillee sorry I can't simply rebase this one as it somehow leads to circular dependency.

File: src/actions/commands/actions.ts [hunk 3]
```diff
@@ -2203,17 +2203,15 @@ class ActionDeleteCharWithDeleteKey extends BaseCommand {
...
-    }
-
-    const state = await new operator.DeleteOperator(this.multicursorIndex).run(vimState, position, position);
-
-    state.currentMode = ModeName.Normal;
-
-    return state;
+  public async execCount(position: Position, vimState: VimState): Promise<VimState> {
+      if (vimState.recordedState.count !== 0) {
+        vimState.recordedState.count = Math.floor(vimState.recordedState.count / 10);
```
Comment (xconverge) [inline src/actions/commands/actions.ts]: What is going on here, not sure I follow

Comment (Chillee) [inline src/actions/commands/actions.ts]: http://vimdoc.sourceforge.net/htmldoc/change.html#<Del>

What the <Del> key does if you have a count in front of it is to remove the last number from the count. So if you typed 100<Del>x, then you would only delete 10 characters.

So I simply divide the count by 10 (which removes the last number).

Comment (Chillee) [inline src/actions/commands/actions.ts]: Come to think of it though, this might not work so well if `<Del>` is pressed when it shouldn't be pressed (in the middle of another operator for example).

Comment (johnfn) [inline src/actions/commands/actions.ts]: Yeah could we leave a comment explaining what's going on here?

Comment (Chillee) [inline src/actions/commands/actions.ts]: Just did :+1:
