### PR TITLE
Fix: Preserve view and pin preview tabs on :w

### LINKED ISSUE #9697: When using preview for open documents, :w won't set the document to "permanent"
**Describe the bug**
When using preview, :w doesn't remove the document from preview. Looking at the code it seems it does that if :w [FILENAME] is used [here](https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/write.ts#L121)

**To Reproduce**

1. Enable preview from quick open and Preview from code navigation
2. Open document
3. Use command :w 
4. Note that the document is still in preview 
5. Type Cmd+s
6. Note the document has left preview

**Expected behavior**
Match save

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

### LINKED ISSUE #9796: Working Tree Tab automatically closed
**Describe the bug**
When I'm in a (Working Tree) tab after clicking on a file that has been changed, make some edits and then `:w` the tab automatically closes. I would expect this of `:wq`.

- Extension (VsCodeVim) version: latest
- VSCode version: latest
- OS: Linux X86_64

### LINKED ISSUE #9800: Bug: Saving in Git diff editor switches to normal editor
**Describe the bug**
When editing on the Git diff editor (the built-in compare view) and saving the file by `:w` command, VS Code unexpectedly switches focus to a normal text editor of the same file.
This starts with VSCodeVim 1.31.0 and does not happen with VSCodeVim 1.30.1. Disabling VSCodeVim stops the issue.

**To Reproduce**

1. Open a repository with changes and open a diff (via Source Control → click a file → Open Changes).
2. Focus the right side of the diff editor and make any edit.
3. Save using `:w`
4. Focus jumps to a normal editor view of the file

**Expected behavior**
Stay in the diff editor on `:w`.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.31.0
- VSCode version: 1.105.1
- OS: Mac OS X 14.7.1

**Additional context**

### PR DESCRIPTION
**Pull request by mccheesy**
- Use Tab API when available to detect preview tabs and only call showTextDocument when needed.
- Ensure saving in compare/diff editors does not switch to a normal editor (fixes #9800, #9796).
- Keep previous behavior of pinning preview tabs on :w so :w matches Cmd+S (fixes #9697).
- Add test coverage for write, including new doc handling logic

references PR #9698
fixes #9800, fixes #9796, fixes #9697 

**Special notes for your reviewer**: Copilot helped with this so if there are any style or coding conventions that I should adjust, I'm happy to update.

### CODE REVIEW

File: src/cmd_line/commands/write.ts [hunk 1]
```diff
@@ -153,6 +156,45 @@ export class WriteCommand extends ExCommand {
...
+   * Determines whether to call showTextDocument when saving.
+   * Avoids disrupting diff views and handles preview tab pinning.
+   */
+  private shouldShowDocument(documentUri: vscode.Uri): boolean {
+    const uriString = documentUri.toString();
+
+    // Modern tab API - more accurate for diff views and preview tabs
+    if (vscode.window.tabGroups) {
+      const allTabs = vscode.window.tabGroups.all.flatMap((group: vscode.TabGroup) => group.tabs);
+      const matchingTab = allTabs.find((tab: vscode.Tab) => this.tabContainsDocument(tab, uriString));
```
Comment (J-Fields) [inline src/cmd_line/commands/write.ts]: Do we need to check all tab groups? Why not just `vscode.tabGroups.activeTabGroup`?

File: src/cmd_line/commands/write.ts [hunk 2]
```diff
@@ -153,6 +156,45 @@ export class WriteCommand extends ExCommand {
...
+   * Handles regular tabs and diff tabs.
+   */
+  private tabContainsDocument(tab: vscode.Tab, uriString: string): boolean {
+    const input = tab.input as any;
+    if (!input) return false;
+
+    // Check common URI properties (covers most tab types)
+    return input.uri?.toString() === uriString ||
+           input.original?.toString() === uriString ||
+           input.modified?.toString() === uriString;
```
Comment (J-Fields) [inline src/cmd_line/commands/write.ts]: Don't love this but it's probably fine

File: src/cmd_line/commands/write.ts (hunk 1 above)
Comment (mccheesy) [reply src/cmd_line/commands/write.ts]: Nice catch - I'm not super familiar with VS Code API and missed that one.

File: src/cmd_line/commands/write.ts [hunk 3]
```diff
@@ -153,6 +156,45 @@ export class WriteCommand extends ExCommand {
...
 
+  /**
+   * Determines whether to call showTextDocument when saving.
+   * Avoids disrupting diff views and handles preview tab pinning.
+   */
+  private shouldShowDocument(documentUri: vscode.Uri): boolean {
+    const uriString = documentUri.toString();
+
+    // Modern tab API - more accurate for diff views and preview tabs
+    if (vscode.window.tabGroups) {
```
[the remark this answers is not in the document]
Comment (mccheesy) [reply src/cmd_line/commands/write.ts]: I think you're right - there's no optional modifier in the docs so it is probably safe to assume it's available. I'll clean this up and get rid of the extraneous fallback case.

File: test/cmd_line/write.test.ts [hunk 4]
```diff
@@ -0,0 +1,400 @@
...
+      showTextDocumentStub = sinon.stub(vscode.window, 'showTextDocument').resolves();
+      tabGroupsStub = sinon.stub(vscode.window, 'tabGroups');
+    });
+
+    teardown(() => {
+      showTextDocumentStub.restore();
+      tabGroupsStub.restore();
+    });
+
+    test('should pin preview tabs when saving', async () => {
```
[the remark this answers is not in the document]
Comment (mccheesy) [reply test/cmd_line/write.test.ts]: Done - I extracted `typeHelloWorld` and `runWriteCommand` functions which reduced a lot of duplication.

**Review by J-Fields — APPROVED** [review]
Thank you!
