### PR TITLE
search operator `\%V`

### LINKED ISSUE #4936: `\%V` not recognized in substitutions within visual selections.
**Describe the bug**
In vim, if you want to do a substitution only on text within a visual selection, you need to use the `\%V` atom. See [vimwiki](https://vim.fandom.com/wiki/Search_and_replace_in_a_visual_selection#Substituting_in_a_visual_selection) on the subject.

However, in VSCode Vim, the same technique appears to just result in "E486: Pattern Not Found" instead of doing the substitution.

**To Reproduce**

1. Create a file with the text `"-Hello-There-"`
2. Visually select the `o-T` in the middle of Hello and There.
3. Run the command: `'<,'>s/\%V-//`
4. See "E486: Pattern Not Found"

**Expected behavior**
In Vim, the resulting text leftover after the above command is `"-HelloThere-"`. I expect the same from VSCode Vim.

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.14.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.0-insider`

### PR DESCRIPTION
**Pull request by elazarcoh**
**What this PR does / why we need it**:
it implements `\%V` in search.
substitution will come in later (maybe in this PR). **Edit:** substitution works out-of-the-box.

**Which issue(s) this PR fixes**
fixes #4936 

**Special notes for your reviewer**:

### CODE REVIEW

File: src/vimscript/pattern.ts [hunk 1]
```diff
@@ -40,6 +40,7 @@ export class Pattern {
   public readonly direction: SearchDirection;
   public readonly regex: RegExp;
   public readonly ignorecase: boolean | undefined;
+  public readonly inselection: boolean | undefined;
```
Comment (J-Fields) [inline src/vimscript/pattern.ts:43]: Make this `inSelection`, please

File: src/vimscript/pattern.ts [hunk 2]
```diff
@@ -83,8 +84,16 @@ export class Pattern {
       fromPosition = args.fromPosition;
     }
 
-    const haystack = vimState.document.getText();
-    const startOffset = vimState.document.offsetAt(fromPosition);
+    const visualSearch = this.inselection && vimState.lastVisualSelection;
+    const haystack = vimState.document.getText(
```
Comment (J-Fields) [inline src/vimscript/pattern.ts:88]: Can you write this like so:
```typescript
let haystack: string;
let searchOffset: number;
if (this.inSelection && vimState.lastVisualSelection) {
  ...
} else {
  ...
}
```

This should make the type assertions unnecessary.

Comment (elazarcoh) [reply src/vimscript/pattern.ts:88]: 👍 will do
I thought you would prefer the constness

File: src/vimscript/pattern.ts [hunk 3]
```diff
@@ -83,8 +84,16 @@ export class Pattern {
...
+      visualSearch
+        ? new Selection(vimState.lastVisualSelection!.start, vimState.lastVisualSelection!.end)
```
Comment (J-Fields) [inline src/vimscript/pattern.ts:90]: No need to import `Selection` - you can make this `new Selection(...)`

File: src/vimscript/pattern.ts [hunk 4]
```diff
@@ -200,12 +210,15 @@ export class Pattern {
       .map((atoms) => {
         let patternString = '';
         let caseOverride: boolean | undefined;
+        let inselection: boolean | undefined;
```
Comment (J-Fields) [inline src/vimscript/pattern.ts:213]: This approach (if there's a `\%V` anywhere, the whole string must be contained in the visual selection) handles the common case, but can you put a `TODO` somewhere noting that it's technically incorrect (as only that zero-length character has to be in the visual selection)?

File: src/vimscript/pattern.ts (hunk 1 above)
Comment (J-Fields) [reply src/vimscript/pattern.ts:43]: Also, please make it a `boolean` and default to `false` in the constructor

File: src/vimscript/pattern.ts (hunk 4 above)
Comment (elazarcoh) [reply src/vimscript/pattern.ts:213]: I wasn't aware of that... I guess I can implement it exactly as described in `:help \%V` if you think it worth it.
Otherwise, I'll add a comment.

File: src/vimscript/pattern.ts (hunk 2 above)
Comment (J-Fields) [reply src/vimscript/pattern.ts:88]: Yeah this is an annoyance I have with typescript (and C++, which I write in my day job) - rust does it right IMO by making blocks expressions... In any case, I like const-ness, but I care more about type safety.

File: src/vimscript/pattern.ts (hunk 4 above)
Comment (J-Fields) [reply src/vimscript/pattern.ts:213]: Nah I don't think it's worth it, at least not now. At some point I'll probably build proper support for all the weird zero-length atoms Vim supports, but for now (all this `Pattern` code is brand new), let's avoid the complexity and satisfy what's probably the only sane use case of `\%V`.

File: src/vimscript/pattern.ts (hunk 1 above)
Comment (elazarcoh) [reply src/vimscript/pattern.ts]: fixed

File: src/vimscript/pattern.ts (hunk 2 above)
Comment (elazarcoh) [reply src/vimscript/pattern.ts]: fixed

File: src/vimscript/pattern.ts (hunk 3 above)
Comment (elazarcoh) [reply src/vimscript/pattern.ts]: fixed

File: src/vimscript/pattern.ts [hunk 5]
```diff
@@ -83,8 +84,20 @@ export class Pattern {
       fromPosition = args.fromPosition;
     }
 
-    const haystack = vimState.document.getText();
-    const startOffset = vimState.document.offsetAt(fromPosition);
+    let haystack: string;
+    let searchOffset: number;
+    if (this.inSelection && vimState.lastVisualSelection) {
+      // TODO: This is not exactly how Vim implements in-selection search (\V%), see :help \%V for more info.
```
Comment (J-Fields) [inline src/vimscript/pattern.ts:90]: typo: `\V%`

File: src/vimscript/pattern.ts [hunk 6]
```diff
@@ -83,8 +84,20 @@ export class Pattern {
...
+      haystack = vimState.document.getText(
+        new Range(vimState.lastVisualSelection.start, vimState.lastVisualSelection.end)
+      );
+      searchOffset = vimState.document.offsetAt(vimState.lastVisualSelection.start);
+    } else {
+      haystack = vimState.document.getText();
+      searchOffset = 0;
```
Comment (J-Fields) [inline src/vimscript/pattern.ts:97]: Something seems a bit buggy when I test it out...

Shouldn't this be `searchOffset = vimState.document.offsetAt(fromPosition)`, and just use that instead of `searchOffset`?

Comment (elazarcoh) [reply src/vimscript/pattern.ts:97]: Hmm, can you describe what seems buggy? maybe I didn't test this use case.

I'll check it again, but the searchOffset is required since the regex match will return the index relative to the selection start, and fromPosition is just where to start searching.

File: src/vimscript/pattern.ts (hunk 5 above)
Comment (elazarcoh) [reply src/vimscript/pattern.ts:90]:
```suggestion
      // TODO: This is not exactly how Vim implements in-selection search (\%V), see :help \%V for more info.
```

File: src/vimscript/pattern.ts (hunk 6 above)
Comment (J-Fields) [reply src/vimscript/pattern.ts:97]: It doesn't always include every match within the visual selection; I think it's starting from the wrong position

Comment (elazarcoh) [reply src/vimscript/pattern.ts:103]: I think it fixed now, by 1a96e70.

**Comment by elazarcoh** [comment]
I seems that substitution is working (almost) out-of-the-box! kudos! In the previous version of the code, before your last refactoring, I saw it would be more painful to implement. 
The only issue with it that it replaces all the lines, instead of one by one. I'll work on it. Do you want it in a separate PR, or we can have both in this one?

**Comment by elazarcoh** [comment]
Substitution works as well. I've added basic tests.
Note that I tagged this PR as "fixes" for the relevant issue (previously it wasn't tagged as such)

**Comment by J-Fields** [comment]
> Substitution works as well (out-of-the-box! kudos for the refactoring!)

Nice, good timing for this PR!

**Review by J-Fields — APPROVED** [review]
Thanks a lot for the PR and for working through feedback quickly!
