### PR TITLE
fix multi line in 'at' and 'it' commands

### LINKED ISSUE #971: Deleting or changing multi-line tag blocks does not work
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

Open an HTML file and move the cursor to a multi-line tag block, e.g. the `d` in this `<div>` tag:

``` html
<div>
    <p>foo bar</p>
</div>
```

Type `dit` or `cit` to delete or edit the multi-line content of the `div` tag.
### What did you expect to happen?

The entire contents of the `div` tag should be deleted, so we're only left with a single line. The cursor moves to the opening `<` of the closing `</div>`, and for `cit`, it also enters insert mode.
### What happened instead?

Nothing
### Technical details:
- VSCode Version: 1.6.1
- VsCodeVim Version: 0.3.8
- OS: Arch Linux

### PR DESCRIPTION
**Pull request by jrenton**
Fixes #971, #1108, #1232, and #1300.

Remaining existing issues: `cit` does not enter insert mode when tag is empty, and it also doesn't return to the correct position when you run `cit` in the closing tag.

### CODE REVIEW

File: src/matching/tagMatcher.ts [hunk 1]
```diff
@@ -1,50 +1,88 @@
...
-    const close = corpus.indexOf(TagMatcher.closeTag, opening + 1);
-    const tagName = tagNameMatch[0];
 
-    // We now know where the opening tag is
-    this.openStart = opening;
-    this.openEnd = close + 1;
+    const stack : any = [];
+    const matchedTags : any = [];
+
+    tags.forEach((tag) => {
```
Comment (johnfn) [inline src/matching/tagMatcher.ts]: Can you just use a simple `for of` loop here?

File: src/matching/tagMatcher.ts [hunk 2]
```diff
@@ -1,50 +1,88 @@
...
+
+      match = TagMatcher.TAG_REGEX.exec(corpus);
     }
-    const close = corpus.indexOf(TagMatcher.closeTag, opening + 1);
-    const tagName = tagNameMatch[0];
 
-    // We now know where the opening tag is
-    this.openStart = opening;
-    this.openEnd = close + 1;
+    const stack : any = [];
```
Comment (johnfn) [inline src/matching/tagMatcher.ts]: Can you give the proper typings here, rather than using `any`? I think it's `{ name: string, type: "close" | "open", startPos: number, endPos: number }[]`

Comment (johnfn) [inline src/matching/tagMatcher.ts]: (And our code formatting conventions are `const stack: type`)

**Comment by johnfn** [comment]
Overall looks good to me. My biggest concern is that we have to parse the entire document every time we do a cit. How is the perf of that in a file such as actions.ts? (And you thought that file was huge for no reason. Of course not, it's to test perf concerns! 😉 )

**Comment by jrenton** [comment]
@johnfn Hah... The performance was a concern of mine too, but I did some tests in very large html files (170,000+ characters) and saw no noticeable delay.

**Comment by xconverge** [comment]
@jrenton I think there was one other comment about using a for of loop, it is in our coding style guide

This is so close that I would like to see it in the next release!

**Comment by theamazingfedex** [comment]
Is there anything that I could do to help expedite this fix getting merged?

**Comment by jrenton** [comment]
@theamazingfedex There are some underlying bugs within VSCodeVim itself outside of this issue relating to assumptions made in regards to changing/deleting text (at least the last I checked). They show themselves through various bugs that still exist with this, including:
- `cit` does not enter insert mode when tag is empty
- When you run `cit` in the closing tag, it doesn't return to the correct position.
- If a closing tag is the first character on a newline, it cannot properly close the tag.

Technically this should be able to be merged, but I kind of gave up when I kept running into bugs that were related to underlying issues with the plugin itself.

**Comment by Chillee** [comment]
So just to be clear, the underlying algorithm for finding the corresponding tags works fine, the issues are mainly related to where the cursor ends up after?

**Comment by jrenton** [comment]
@Chillee Yes

**Comment by Chillee** [comment]
Do you think they're fixable (just a massive pain), or is there some fundamental limitation with our current code structure?

**Comment by johnfn** [comment]
There aren't any fundamental limitations to getting tag text objects to work. It's just more work. :)
