### PR TITLE
Fix :tabm to use moveActiveEditor command

### LINKED ISSUE #2401: Refactor: Use `moveActiveEditor` instead of `activeEditorMove`
Documentation: 
* https://github.com/Microsoft/vscode/issues/8234
* https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

```
moveActiveEditor - Move the active editor by tabs or groups

    Active editor move argument

    Argument Properties:
        'to': String value providing where to move.
        'by': String value providing the unit for move. By tab or by group.
        'value': Number value providing how many positions or an absolute position to move.
```

### PR DESCRIPTION
**Pull request by arussellk**
**What this PR does / why we need it**:
Updates `:tabm` to use `moveActiveEditor` so that it works.

**Which issue(s) this PR fixes**:
Fixes #2401 

**Special notes for your reviewer**:
I did not write automated tests for this because I could not figure out how to inspect an editor index position. Does anyone know how to access that information?

### CODE REVIEW

File: src/cmd_line/commands/tab.ts [hunk 1]
```diff
@@ -119,17 +119,17 @@ export class TabCommand extends node.CommandBase {
...
-        if (this._arguments.count !== undefined) {
-          if (this._arguments.count === 0) {
-            vscode.commands.executeCommand('activeEditorMove', { to: 'first' });
-          } else {
-            vscode.commands.executeCommand('activeEditorMove', {
-              to: 'position',
-              amount: this._arguments.count,
-            });
-          }
+        // Documentation: https://github.com/Microsoft/vscode/issues/8234#issuecomment-234573410
```
Comment (jpoon) [inline src/cmd_line/commands/tab.ts]: Can you remove the comment? I'm not a fan of having such comments in the code.

**Comment by jpoon** [comment]
I left a comment, but I'm good to have this merged without a UT -- don't know of an API to inspect the editor index.

**Comment by arussellk** [comment]
For future reference, the documentation for the `moveActiveEditor` command is buried in a comment on Github here: https://github.com/Microsoft/vscode/issues/8234#issuecomment-234573410

File: src/cmd_line/commands/tab.ts (hunk 1 above)
Comment (arussellk) [reply src/cmd_line/commands/tab.ts]: Comment removed. I put the link on this issue instead.
