### PR TITLE
[p, [p, gp and gP

### LINKED ISSUE #407: p/P cursor position is wrong
### Issue Summary

If you run `p/P` after yank, the cursor should be at the first non-whitespace character instead of the very beginning of the line.

### PR DESCRIPTION
**Pull request by rebornix**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] It builds and tests pass (e.g `gulp tslint`)

1. Fix #407.
2. Support [p, [p, gp and gP and have all features covered with test cases.

### CODE REVIEW

File: src/actions/actions.ts [hunk 1]
```diff
@@ -779,14 +779,27 @@ export class PutCommand extends BaseCommand {
...
         const dest = before ? position : position.getRight();
+        let text = register.text;
 
         if (register.registerMode === RegisterMode.CharacterWise) {
           await TextEditor.insertAt(text, dest);
         } else {
+          if (adjustIndent) {
+            // Adjust indent to current line
+            let indentationWidth = TextEditor.getLeftIndentation(TextEditor.getLineAt(position).text);
+            let firstLineIdentationWidth = TextEditor.getLeftIndentation(text.split('\n')[0]);
```
Comment (johnfn) [inline src/actions/actions.ts]: Why do you have to split on \n if you already got a single line?

File: src/textEditor.ts [hunk 2]
```diff
@@ -107,5 +107,54 @@ export class TextEditor {
     static isLastLine(position : vscode.Position): boolean {
         return position.line === (vscode.window.activeTextEditor.document.lineCount - 1);
     }
+
+    static getLeftIndentation(line: string): number {
```
Comment (johnfn) [inline src/textEditor.ts]: You can just name this getIndentation

File: src/textEditor.ts [hunk 3]
```diff
@@ -107,5 +107,54 @@ export class TextEditor {
...
+        let tabSize = vscode.workspace.getConfiguration("editor").get<number>("tabSize");
+        let firstNonWhiteSpace = line.match(/^\s*/)[0].length;
```
Comment (johnfn) [inline src/textEditor.ts]: We have a method on positions that gets the first nonwhitespace char already.

File: src/textEditor.ts [hunk 4]
```diff
@@ -107,5 +107,54 @@ export class TextEditor {
...
+        let visibleColumn: number = 0;
+
+        if (firstNonWhiteSpace >= 0) {
+            line.substring(0, firstNonWhiteSpace).split("").forEach(char => {
```
Comment (johnfn) [inline src/textEditor.ts]: I prefer `for (const char of line.substring(0, firstNonWhiteSpace))`

File: src/textEditor.ts [hunk 5]
```diff
@@ -107,5 +107,54 @@ export class TextEditor {
...
+        } else {
+            return -1;
+        }
+
+        return visibleColumn;
+    }
+
+    static adjustIndentation(line: string, screenCharacters: number): string {
+        let tabSize = vscode.workspace.getConfiguration("editor").get<number>("tabSize");
+        let insertTabAsSpaces = vscode.workspace.getConfiguration("editor").get<boolean>("insertSpaces");
```
Comment (johnfn) [inline src/textEditor.ts]: 👍

File: src/textEditor.ts [hunk 6]
```diff
@@ -107,5 +107,54 @@ export class TextEditor {
...
+                }
+            });
+        } else {
+            return -1;
+        }
+
+        return visibleColumn;
+    }
+
+    static adjustIndentation(line: string, screenCharacters: number): string {
```
Comment (johnfn) [inline src/textEditor.ts]: Rename to `setIndentationLevel`

File: src/textEditor.ts (hunk 3 above)
Comment (rebornix) [inline src/textEditor.ts]: I see that when I operate on Position but here we are operating on string most of the time and this functionality is real simple, so I just moved it here. Maybe we can write some utility functions to handle all these kind of string matching?

File: src/textEditor.ts (hunk 4 above)
Comment (rebornix) [inline src/textEditor.ts]: Fixed.

**Comment by rebornix** [comment]
Adjust the code except the `findFirstNonWhitespace`, not quire sure what's the best place to put it yet.

**Comment by johnfn** [comment]
LGTM 👍
