### PR TITLE
Exclude :w, :q, and :wq from dot command

### LINKED ISSUE #6829: Exclude `:w`, `:q`, and `:wq` from dot command
**Describe the bug**
Dot command is able to repeat write (`:w`), close (`:q`) and write + close (`:wq`).

**To Reproduce**

Write:
1.  Open a file
2.  Go to insert mode and type `hello`
3.  Exit insert mode and write changes to file `:w`
4.  Type `.`

Close/write+close:
1.  Open a file
2.  Go to insert mode and type `hello`
3.  Exit insert mode
4. Use `:wq` or `:q!`
5. Reopen the buffer and type `.`

**Expected behavior**
Write, close and write+close should be excluded from dot command.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `v1.21.4`
- VSCode version: `v1.57.1`
- OS: `Linux`

### PR DESCRIPTION
**Pull request by justalmill**
**What this PR does / why we need it**:

Adds a boolean property "isRepeatableWithDot" to exCommand to identify commands which should and should not be repeatable via dot command.

Adds a boolean property "lastCommandDotRepeatable" to vimState to keep track of if the last command executed is repeatable via dot command and should update the globalState.previousFullAction.

Resolves an issue where save, quit, and savequit commands would be treated as repeatable for the purpose of the dot command, making the dot command less effective.

**Which issue(s) this PR fixes**

fixes #6829 

**Special notes for your reviewer**:

New to the code base and new to open source, feedback appreciated!

### CODE REVIEW

File: src/cmd_line/commandLine.ts [hunk 1]
```diff
@@ -288,6 +288,9 @@ export class ExCommandLine extends CommandLine {
       }
     }
 
+    // Update state if this command is repeatable via dot command.
+    vimState.lastCommandDotRepeatable = !!this.command?.isRepeatableWithDot;
```
Comment (J-Fields) [inline src/cmd_line/commandLine.ts:292]:
```suggestion
    vimState.lastCommandDotRepeatable = this.command?.isRepeatableWithDot ?? false;
```

File: src/state/recordedState.ts [hunk 2]
```diff
@@ -282,7 +282,7 @@ export interface IBaseAction {
   readonly isOperator: boolean;
   readonly isCommand: boolean;
   readonly isJump: boolean;
-  readonly canBeRepeatedWithDot: boolean;
+  readonly actionCreatesUndoPoint: boolean;
```
Comment (J-Fields) [inline src/state/recordedState.ts:285]:
```suggestion
  readonly createsUndoPoint: boolean;
```

**Comment by J-Fields** [comment]
Much appreciated, great first open source contribution! 🙂
