### PR TITLE
Fix delete line with CRLF (#743)

### LINKED ISSUE #743: ddp appends extra newline when pasting
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`ddp`

### What did you expect to happen?

Delete current line and paste below following line.

### What happened instead?

Delete current line and paste deleted line _plus an extra trailing newline_ below following line.

### Technical details:

* VSCode Version: 1.5.1
* VsCodeVim Version: 0.1.10
* OS: Windows 10 x64

### PR DESCRIPTION
**Pull request by jgoz**
Fixes #743.

Delete was not taking a possible `\r` into consideration when performing a linewise delete, which resulted in an extra linebreak being appended to the line if it later was pasted.

Also removed a duplicate test related to this functionality (`"Can copy to a register"`). That test was failing on Windows with `"files.eol": "crlf"`, but now passes after this change.

### CODE REVIEW

**Comment by xconverge** [comment]
Why is the copy to a register test removed

**Comment by jgoz** [comment]
@xconverge 

> Why is the copy to a register test removed

Per the PR description:

> Also removed a **duplicate** test related to this functionality (`"Can copy to a register"`). That test was failing on Windows with `"files.eol": "crlf"`, but now passes after this change.

As stated, the removed test was an exact duplicate of the one above it. The only reason I saw it is because the test was failing prior to my change.

**Comment by xconverge** [comment]
Woops sorry totally missed that from my phone

I wonder why there was a duplicate..

**Comment by jgoz** [comment]
No problem! Might be a merge conflict artifact.

File: src/actions/actions.ts [hunk 1]
```diff
@@ -1062,7 +1062,8 @@ export class DeleteOperator extends BaseOperator {
         let text = vscode.window.activeTextEditor.document.getText(new vscode.Range(start, end));
 
         if (registerMode === RegisterMode.LineWise) {
-          text = text.slice(0, -1); // slice final newline in linewise mode - linewise put will add it back.
+          // slice final newline in linewise mode - linewise put will add it back.
+          text = text[text.length - 2] === '\r' ? text.slice(0, -2) : text.slice(0, -1);
```
Comment (johnfn) [inline src/actions/actions.ts]: Can you ensure the line actually ends in `\r\n`?

Comment (jgoz) [inline src/actions/actions.ts]: Done.

**Comment by johnfn** [comment]
Excellent! Thank you, @jgoz!
