### PR TITLE
Fix recording macro not showing after 'setText'

### LINKED ISSUE #4753: confusing macro recording
When recording macro, I notice that the state being displayed at the bottom bar can be quite confusing. It looks like the information ```Recording @qr``` can easily be masked. For example:

- perform a write ```:w```
- then start a macro recording: ```qr```
- in this case nothing gets displayed on the bottom bar about the macro (I still see only '"space_age.cpp" 48L 1462C Written' displayed, nothing about the macro status).

By contrast:

- starting from the last previous point:
- go to insert mode: ```i```
- then the displayed information becomes '--INSERT-- Recording @qr' 

So the macro was well being recorded, but the info message was being hidden.

A fix for this is, each time one wants to record a macro:

- press ```i```
- press ```ESC```
- then press ```q```+CHAR, and the info is well displayed.

But still, think this may be confusing, at least this confused me for 10 minutes or so until I understand this :) .

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
Fix recording macro not showing after 'setText'
- If 'setText' was called somewhere else like when undoing or when ':w'
the Recording info would be lost
- This commit makes it so that after the next key press we will get the
info back, this is the same behavior as Vim

**Which issue(s) this PR fixes**
Fixes #4753

**Special notes for your reviewer**:
The `Recording @` message was being erased because every time the `StatusBar.setText` is called it replaces the existing text with the new message.

This happens, for example, when the `:write`  command calls `setText` or when you undo something, which might happen in the middle of the macro recording and erases the recording message.

The message would only update again with the `Recording @` after a mode change. This makes it update after the next key press, which means if you undo you get the undo message until you press some key which replaces that message with the clear text that includes the macro recording.

This is the Vim behavior but I think Neovim always shows it. We could make it always show up by appending it to `text` on the `StatusBar.setText(text)` function as well. Some users might prefer it that way.

### CODE REVIEW

File: src/mode/modeHandler.ts [hunk 1]
```diff
@@ -333,7 +333,8 @@ export class ModeHandler implements vscode.Disposable {
       // Clear the status bar of high priority messages if the mode has changed or the view has scrolled
```
Comment (J-Fields) [inline src/mode/modeHandler.ts:333]: Can you update this comment please?

**Comment by J-Fields** [comment]
> This is the Vim behavior but I think Neovim always shows it

I think I have an old version of neovim installed, but this doesn't seem to be the case for me

**Comment by J-Fields** [comment]
Testing this out again in neovim, it seems like there's just a timeout. I like this behavior, though, and it's a quick fix, so let's go with it at least for now.
