### PR TITLE
`jj` cursor position fix for #1418

### LINKED ISSUE #1418: Wrong cursor position entering normal mode
### What did you do?

Add this to config:
```
 "vim.insertModeKeyBindings": [
        {
            "before": [
                "d",
                "f"
            ],
            "after": [
                "<Esc>"
            ]
        }
    ]
```

### What did you expect to happen?

to work keys same as in vim and same as <Esc>

### What happened instead?

put cursor in the middle of text and press df, it enters normal mode, but places cursor one position further than <Esc>

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: macOS

### PR DESCRIPTION
**Pull request by prog666**
**Which issue(s) this PR fixes**
fixes #1418

**Special notes for your reviewer**: tried to make test, but tests are made in the way that `jj` not actually passed to editor.

### CODE REVIEW

**Comment by Chillee** [comment]
I think @jpoon recently added functionality for testing remappings. Have you tried the method [here](https://github.com/VSCodeVim/Vim/blob/master/test/configuration/configuration.test.ts)?

**Comment by prog666** [comment]
it tests that keys are replaced with correct keys, but that is not the case

**Comment by prog666** [comment]
anyway, im using vim with my fix for 3 days now, everything is ok

**Comment by prog666** [comment]
What is stopping us from merging this pr?

**Comment by AlexArendsen** [comment]
+1 I'd love to see this merged in too.

**Comment by Chillee** [comment]
@prog666 Sorry, I didn't immediately merge this because I was confused what the error was (I think partially because the repro in the issue linked isn't related to the title of this PR). After playing around with it a bit though, I see what the issue was.

LGTM!

**Comment by prog666** [comment]
what are we waiting for?

File: src/common/motion/position.ts [hunk 1]
```diff
@@ -376,9 +376,9 @@ export class Position extends vscode.Position {
    * Gets the position one to the left of this position. Does not go up line
    * breaks.
    */
-  public getLeft(): Position {
+  public getLeft(count: number = 1): Position {
     if (!this.isLineBeginning()) {
```
Comment (jpoon) [inline src/common/motion/position.ts]: Can you update this check to ensure that we don't go past the beginning of the line?

File: src/common/motion/position.ts [hunk 2]
```diff
@@ -376,9 +376,9 @@ export class Position extends vscode.Position {
    * Gets the position one to the left of this position. Does not go up line
```
Comment (jpoon) [inline src/common/motion/position.ts]: Please update this comment.

File: src/common/motion/position.ts (hunk 1 above)
Comment (prog666) [reply src/common/motion/position.ts]: there's no check for getRight()

**Comment by prog666** [comment]
@jpoon done

**Comment by jpoon** [comment]
On vacation in Africa at the moment. We'll be back to hotel tomorrow and I can take a look then. Otherwise @chillee can merge assuming my comments were addressed.

**Comment by Chillee** [comment]
Looks like both of jpoon's comments have been addressed. I'm gonna merge this. Thanks!
