### PR TITLE
Fixes #1674: repeating . with characters like " or ) leaves cursor in wrong place

### LINKED ISSUE #1674: dot command does not work properly when inserting <Tab>/"/'/(/{/[
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.x
- **VsCodeVim Version**: 0.7.0
- **OS**: Linux

Failure mode for tabs as spaces with the dot command:

**What happened**:
1. Press `i` to enter insert mode
2. Press `<Tab>` to insert tabs as spaces
3. Press `<ESC>` to exit insert mode
4. Press `.` to repeat the last command

**What did you expect to happen**: 
* Insert another `<Tab>` (as spaces)

**What happened instead**: 
* Cursor moves left one character and nothing was inserted

Failure mode for inserting `"` (double quote) with the dot command (the same behavior happens when inserting any of the following chars `(`, `{`, `'`, `[`):

**What happened**:
1. Go to the first line of an indented paragraph
2. Press `i` to enter insert mode
3. Press `"` (double quote), to insert a double quote
4. Press `<ESC>` to exit insert mode
5. Go down one line by pressing `j`
6. Press `.` to repeat the last command
7. Go down one line by pressing `j`
8. Press `.` to repeat the last command yet again

**What did you expect to happen**: 
* Insert a `"` (double quote) to the beginning of the next line

**What happened instead**: 
* Cursor moves left one character each time the "dot" command is used
  * This causes the insertion of the next `"` (double quote) to be in the wrong place

### PR DESCRIPTION
**Pull request by Chillee**
So this one is kinda weird.

I'll put my main comments in the code review.

### CODE REVIEW

File: src/mode/modeHandler.ts [hunk 1]
```diff
@@ -883,24 +883,11 @@ export class ModeHandler implements vscode.Disposable {
...
-            x.startsWith("'")  ||
-            x.startsWith("\"") ||
-            x.startsWith("{");
-
           // Push document content change to the stack
           lastAction.contentChanges = lastAction.contentChanges.concat(
             vimState.historyTracker.currentContentChanges.map(x => ({
               textDiff: x,
-              positionDiff: startsWithPairedCharacter(x.text) ? new PositionDiff(0, -1) : new PositionDiff(0, 0),
+              positionDiff: new PositionDiff(0, 0)
```
Comment (xconverge) [inline src/mode/modeHandler.ts]: Can this be removed now?

**Comment by Chillee** [comment]
As the issue that was the cause of the confusing code no longer replicates (https://github.com/VSCodeVim/Vim/issues/1389), I'm gonna merge this PR.
