### PR TITLE
Fix path delimiter issue with neovim detection

### LINKED ISSUE #4902: Not able to autodetect my Neovim path
**Describe the bug**
According to [the docs](https://github.com/VSCodeVim/Vim#neovim-integration), I should be able to leave `neovimPath` blank and it will attempt to detect according to my PATH. The code indeed shows that it is trying to do that, but something is wrong:
image

As a side note, the setting description also does not match the documentation:
image

Ideally we can update this as part of this issue

**To Reproduce**

1.  Go to settings
2. Leave "Vim: Neovim Path" blank
3. Click the checkbox for "Vim: Enable Neovim"

**Expected behavior**
`nvim` which is in my path gets detected

```
$ which nvim
/usr/local/bin/nvim
```

**Screenshots**
Included in body

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.46.0-insider
- OS: Mac OSX 10.15.4

**Additional context**
```
$ echo $PATH
/Users/Mike/.rbenv/shims:/Users/Mike/.rbenv/bin:/Users/Mike/.cargo/bin:/Users/Mike/Library/Python/3.6/bin:/Users/Mike/bin:/Users/Mike/.nvm/versions/node/v13.12.0/bin:/Users/Mike/.rbenv/shims:/Users/Mike/.rbenv/bin:/Users/Mike/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/Mike/.rvm/bin:/Users/Mike/Library/Python/3.7/bin/
```

### PR DESCRIPTION
**Pull request by mhchen**
**What this PR does / why we need it**:
Mac/Linux uses `:` for the `PATH` delimiter. Using `path.delimiter` to be platform-agnostic.

**Which issue(s) this PR fixes**
Fixes #4902

**Special notes for your reviewer**:

### CODE REVIEW

File: src/configuration/validators/neovimValidator.ts [hunk 1]
```diff
@@ -30,7 +29,7 @@ export class NeovimValidator implements IConfigurationValidator {
             });
           }
         }
-        await promisify(execFile)(config.neovimPath, ['--version']);
+        execFileSync(config.neovimPath, ['--version']);
```
Comment (mhchen) [inline src/configuration/validators/neovimValidator.ts:32]: Updated this to `execFileSync` because we're essentially using it synchronously and it's much easier to mock.
