### PR TITLE
fix: clean-up neovim processes. closes #2038

### LINKED ISSUE #2038: Multiple instances of nvim.exe process
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Maybe BUG REPORT**:

It seems that nvim.exe proces is spawn for each tab I edit. These processes are still running even I close all tabs (VS Code is still running but without any opened tab). This is not a big problem ... but after 8 hours of work my Task Manager looks like this

image

**Environment**:

- **VSCode Version**: 1.16.1
- **VsCodeVim Version**: 0.10.1
- **OS**:  Windows 10

**What did you expect to happen**: 
Some cap on number of active nvim processes. e.g max 10 is kept running. Oldest are closed

**How to reproduce it**:

Open multiple files. Then close them. Keep your editor running

### PR DESCRIPTION
**Pull request by jpoon**
**What this PR does / why we need it**: Properly kills neovim processes on exit. Refactoring of neovim to a class. 

**Which issue(s) this PR fixes** #2038

**Special notes for your reviewer**:

### CODE REVIEW

File: src/cmd_line/commandLine.ts [hunk 1]
```diff
@@ -33,14 +33,14 @@ export class CommandLine {
...
-        await Neovim.command(vimState, command);
+        await vimState.nvim.run(vimState, command);
       } else {
         await cmd.execute(vimState.editor, vimState);
       }
     } catch (e) {
       if (e instanceof VimError) {
         if (e.code === ErrorCode.E492 && configuration.enableNeovim) {
-          await Neovim.command(vimState, command);
+          await vimState.nvim.run(vimState, command);
```
Comment (jpoon) [inline src/cmd_line/commandLine.ts]: @chillee, I don't quite understand this bit. If it's `E492` we want to retry running neovim again?

Comment (Chillee) [reply src/cmd_line/commandLine.ts]: When we pass the command into our own command line command/parser, there's lots of cases in which the parser will error (since it doesn't support a lot of commands).

If the parser can't parse it, then we try sending it to the neovim parser (which may support the command).

Comment (Chillee) [reply src/cmd_line/commandLine.ts]: So basically, the above code that detects if the command is neovim capable and passes it to Neovim only works for commands that we **know** are neovim capable. There's lots of commands that we don't implement, and the parser errors out in those cases.

**Comment by jplew** [comment]
just want to say that v11.0 has restored neo-vim functionality for me. Neo-vim features were broken for me in 10.3 but this patch seems to have fixed it.
