### PR TITLE
fixes #1145

### LINKED ISSUE #1145: Three-letter otherModesKeyBindingsNonRecursive remappings fail to match
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Added remapping with three letters, like:
```javascript
  "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": [ "<leader>", "f", "s" ],
      "after": [],
      "commands": [{
        "command": "workbench.action.files.save",
        "args": []
      }]
    },
    {
      // Just some random letters to make sure it wasn't a problem with the leader key
      "before": [ "g", "y", "z" ],
      "after": [],
      "commands": [{
        "command": "workbench.action.quickOpen",
        "args": []
      }]
    }
  ]
```
Then pressed the key combination

### What did you expect to happen?
The command to run.

### What happened instead?
The third letter's command (`s` in the case of `<leader>fs`) runs.

Also, when I press the first letter, it appears in the status line. But when I press the second letter, the status line goes back to blank.

If I change the remapping to two characters, it works as expected.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9, also tried master
* OS: Windows 10

I tried tracing the problem with the debugger, but other than seeing that `Remapper.sendKey` doesn't find a remapping in the three-character case, I couldn't figure out what was up. If someone has a better idea of where to look, I'd be happy to dig into it further. I think this is related to why `"<space>", "f", "s"` doesn't work in https://github.com/VSCodeVim/Vim/issues/1132.

### PR DESCRIPTION
**Pull request by xconverge**
should work...tested the few cases that were in the issue reported

### CODE REVIEW

File: src/mode/remapper.ts [hunk 1]
```diff
@@ -120,8 +125,17 @@ class Remapper {
       }
 
       vimState.isCurrentlyPerformingRemapping = false;
-
       return true;
+    } else {
+      // Check to see if a remapping could potentially be applied when more keys are received
+      for (let remap of this._remappings) {
```
Comment (johnfn) [inline src/mode/remapper.ts]: Is it possible to make this a return value rather than returning it implicitly as a class property?

Comment (xconverge) [inline src/mode/remapper.ts]: Want me to just make a getter for it? It is already used on lines 77 and 83

Comment (xconverge) [inline src/mode/remapper.ts]: or do you mean break off the function into a isRemappingPotential() function that takes the current keystrokes as an input?

Comment (johnfn) [inline src/mode/remapper.ts]: I mean could we return this value from `sendKey` somehow?

**Comment by xconverge** [comment]
this also fixes #1222

File: src/mode/remapper.ts (hunk 1 above)
Comment (xconverge) [inline src/mode/remapper.ts]: Unless I am missing something obvious that you can see pretty clearly...

It is definitely possible, the problem I see is that we call handleKeyEvent, which calls sendKey, then it calls handleKeyEventHelper which uses the property

I could make a data structure that returned a few properties but I don't think it will end up being cleaner...

sendkey only returning a boolean seems to make sense to me, I would really only change this to return a true/false/maybe with the data structure anyways

Comment (johnfn) [inline src/mode/remapper.ts]: I see what you mean, it would be annoying to thread through. OK, a getter is fine.

**Comment by xconverge** [comment]
@johnfn should be good to go now, let me know if there is anything else
