### PR TITLE
Vim Settings

### LINKED ISSUE #481: :set hlsearch not working
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?
I was trying to ":set hlsearch"
### What did you expect to happen?
I would my expect my search would be highlighted. 
### What happened instead?
Not highlighted.
### Technical details:

* VSCode Version:1.3.1
* VsCodeVim Version: 0.1.3
* OS: Windows 10

### LINKED ISSUE #487: `w` should/could respect `wordSeparators` settings
My `wordSeparators` settings doesn't have `$`.

```js
  // Characters that will be used as word separators when doing word related navigations or operations
  "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
```

### What did you do?

I edited my `settings.json` so that `wordSeparators` does *not* have `$`.
Then
The cursor in a file was here
```
foo$ + bar$
^
|
```
I used `w` in normal mode to skip to the next word.

### What did you expect to happen?

Cursor to be here
```
foo$ + bar$
     ^
     |
```

### What happened instead?

```
foo$ + bar$
   ^
   |
```

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: Mac OS X El Capitan

### PR DESCRIPTION
**Pull request by rebornix**
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] It builds and tests pass (e.g `gulp tslint`)

This feature is related to #433, #463, #487 and #481. The basic idea is maintaining a singleton of Vim Settings. This Vim Seting object reads configuration from User Settings, `.vimrc`, Code configuration then our own (VSCodeVim) default value.

- [x] Singleton Vim Settings
- [x] Load `vim.{xxx}` section
- [x] Map Vim configure to Code if there is any overlap
- [x] Fix #487
- [x] Fix #481
- [ ] `.vimrc` loading
- [ ] Auto update (monitoring both Code's configuration and `.vimrc`)

### CODE REVIEW

File: src/configuration/configuration.ts [hunk 1]
```diff
@@ -0,0 +1,277 @@
...
+
+/**
+ * Vim option override sequence.
+ * 1. `:set {option}` on the fly
+ * 2. VS Code Vim configuration section && overlap configurations between Code and Vim
+ * 3. TODO .vimrc.
+ * 4. VSCodeVim flavored Vim option default values
+ */
+export class Configuration {
+  private static _instance: Configuration;
```
Comment (johnfn) [inline src/configuration/configuration.ts]: Use optional types!

private static _instance: Configuration | null;

**Comment by rebornix** [comment]
Currently you will see some problems as we have bugs in Code https://github.com/Microsoft/vscode/issues/9731.

**Comment by johnfn** [comment]
> .vimrc loading

I have no qualms at all about you leaving this to another PR.

> Auto update (monitoring both Code's configuration and .vimrc)

This would be very awesome, but low priority. Most people expect to have to restart their editor anyways.

File: package.json [hunk 2]
```diff
@@ -145,6 +145,30 @@
                 "vim.scroll": {
                     "type": "number",
                     "description": "Number of lines to scroll with CTRL-U and CTRL-D commands."
+                },
+                "vim.tabstop": {
```
Comment (johnfn) [inline package.json]: You don't know how happy it makes me to see we support all this stuff. My god, it's like we're actually making a real Vim plugin!!!

File: src/actions/actions.ts [hunk 3]
```diff
@@ -1247,7 +1248,10 @@ class MCommandMoveHalfPageDown extends BaseMovement {
   keys = ["ctrl+d"];
 
   public async execAction(position: Position, vimState: VimState): Promise<Position> {
-    return new Position(Math.min(TextEditor.getLineCount() - 1, position.line + vimState.settings.scroll), position.character);
+    return new Position(
+      Math.min(TextEditor.getLineCount() - 1, position.line + <number> Configuration.getInstance().get("scroll")),
```
Comment (johnfn) [inline src/actions/actions.ts]: I think the number cast can go inline like so

`.get<number>("scroll")`

Or something like that???

File: src/configuration/configuration.ts [hunk 4]
```diff
@@ -0,0 +1,280 @@
...
+  public static allOptions: { [key: string]: BaseOptionDetails } = {};
+}
+
+export function RegisterOption(optionDetails: typeof BaseOptionDetails): void {
+  let newOption = new optionDetails();
+  newOption.initialize();
+  OptionMap.allOptions[newOption.id] = newOption;
+}
+
+@RegisterOption
```
Comment (johnfn) [inline src/configuration/configuration.ts]: After having to deal with this pattern for 3000 lines of action.ts, I am beginning to regret it. Fixing that file will be hard, but fixing this one will be easy!!! 😀 

My suggestion would instead to be to make an interface called BaseOptionDetails that looks like this

```
interface BaseOption { //yep, use templating plz
    vimName: string;
    vscodeName: string?;
    defaultValue: OptionValue;
}
```

Then do something like

```
var options = [
    { vimName: "useSolidBlockCursor", defaultValue: false },
    { vimName: "useCtrlKeys", defaultValue: false },
    // ETC.
]
```

Then restructure the rest of the code around that.

I can explain exactly why I want to do this, but, long story short, classes are very prohibitive/clunky for our purposes, and we don't really use them for all that much that basic objects can't do.

File: src/configuration/configuration.ts [hunk 5]
```diff
@@ -0,0 +1,280 @@
...
+    }
+  }
+}
+
+@RegisterOption
+class OptionInsertSpaces extends BaseOptionDetails {
+  id = "expandtab"; // aka insertSpaces
+  defaultValue = false;
+
+  fetchCodeConfiguration() {
```
Comment (johnfn) [inline src/configuration/configuration.ts]: There is a bunch of duplication between this and OptionTabStop that you're going to need to remove as well.

File: src/actions/actions.ts [hunk 6]
```diff
@@ -1247,7 +1248,10 @@ class MCommandMoveHalfPageDown extends BaseMovement {
   keys = ["ctrl+d"];
 
   public async execAction(position: Position, vimState: VimState): Promise<Position> {
-    return new Position(Math.min(TextEditor.getLineCount() - 1, position.line + vimState.settings.scroll), position.character);
+    return new Position(
```
Comment (johnfn) [inline src/actions/actions.ts]: :+1:

File: src/cmd_line/subparsers/setoptions.ts [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+
+  if (option.startsWith("no")) {
+    // :se[t] no{option}  Toggle option: Reset, switch it off.
+    return {
+      name: option.substring(2, option.length),
+      operator: node.SetOptionOperator.Reset
+    };
+  }
+
+  if (option.includes('=')) {
```
Comment (johnfn) [inline src/cmd_line/subparsers/setoptions.ts]: "foo=bar" should not parse as a single word, but rather 3 separate words: ["foo", "=", "bar"]. Same with ":".

I realize Vim has some slightly bizarre rules about whitespace, but I think it's okay to be more permissive than they are if it is also easier to code it that way.

File: src/configuration/configuration.ts [hunk 8]
```diff
@@ -0,0 +1,280 @@
...
+
+    targetOption.value = value;
+  }
+
+  /**
+   * Return a value of option from vim settings.
+   * @param vim option.
+   * @param defaultValue A value should be returned when no value could be found, is `undefined`.
+   */
+  get(option: string, defaultValue?: OptionValue): OptionValue | undefined {
```
Comment (johnfn) [inline src/configuration/configuration.ts]: I don't actually like this API. I would prefer to have every setting listed off sort of like so

```
class Configuration {
    tabstop: number;
    smartcase: boolean;
    ignorecase: boolean;
}
```

etc.

The advantages here are 

1. All settings accesses will be strongly typed
2. Autocomplete will work for our settings

File: src/configuration/configuration.ts (hunk 4 above)
Comment (rebornix) [inline src/configuration/configuration.ts]: The one you suggest is what exactly I did at first but later on I found it became difficult to add handlers then I switch to our Action inheritance magic, lol ...

But now it seems I'm over designing.

Comment (johnfn) [inline src/configuration/configuration.ts]: Haha, yeah. The logic will have to go somewhere. I just want to separate the logic from the data.

**Comment by rebornix** [comment]
Did a huge refactor to VimSettings. I can't imagine before that we can make this real simple with a little bit hack of Accessor Decorator.

With the new design, we only have one single Class/Object maintaining all Vim options' definition, intialization and updating. It's called `Configuration`.

## Access `Configuration`
Use `Configuration.getInstance()`, it's the only way of getting an object of Configuration and yeah we make it a Singleton. 

`getInstance()` is the only public method in `Configuration`.

## Access a single Vim option
1. Get: `Configuration.getInstance().{OptionName}`, eg, `Configuration.getInstance().tabstop`.
2. Set: `Configuration.getInstance().{OptionName} = {NewValue}`, eg, `Configuration.getInstance().tabstop = 4`.
3. Bracket notation: eg, `Configuration.getInstance()["tabstop"]`, `Configuration.getInstance()["tabstop"] = 4`.

Lastly, we will support `.vimrc` later on and the update of `.vimrc` should trigger `Configuration` to update automatically.

**Comment by rebornix** [comment]
Fix #279 as it's real easy to implement based on current Setting design, just 20 lines of code change.

**Comment by johnfn** [comment]
Hey @rebornix is this good to go? Or are you still working on it?

**Comment by rebornix** [comment]
I updated the code after our last sync up on Slack. Feel free to review and let me know what else you think can be improved.

File: src/configuration/configuration.ts [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+export class Configuration {
+  private static _instance: Configuration | null;
+
+  constructor() {
+    /**
+     * Load Vim options from User Settings.
+     */
+    let vimOptions = vscode.workspace.getConfiguration("vim");
+    /* tslint:disable:forin */
+    // Disable forin rule here as we make accessors enumerable.`
```
Comment (johnfn) [inline src/configuration/configuration.ts]: Can we use for of here as well?

File: src/configuration/configuration.ts [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+
+  public static getInstance(): Configuration {
+    if (Configuration._instance == null) {
+      Configuration._instance = new Configuration();
+    }
+
+    return Configuration._instance;
+  }
+
+  useSolidBlockCursor: boolean = false;
```
Comment (johnfn) [inline src/configuration/configuration.ts]: Yess, this is great.

File: src/configuration/configuration.ts [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+ * 4. If user doesn't set the option explicitly
+ *    a. we don't have a similar setting in Code, initialize the option as default value.
+ *    b. we have a similar setting in Code, use Code's setting.
+ *
+ * Vim option override sequence.
+ * 1. `:set {option}` on the fly
+ * 2. TODO .vimrc.
+ * 2. `vim.{option}`
+ * 3. VS Code configuration
+ * 4. VSCodeVim flavored Vim option default values
```
Comment (jpoon) [inline src/configuration/configuration.ts]: Can you add this to the `readme` explaining which settings take priority?

File: src/configuration/configuration.ts [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+  ignorecase: boolean = true;
+  smartcase: boolean = true;
+
+  @overlapSetting({ codeName: "tabSize", default: 8})
+  tabstop: number;
+
+  @overlapSetting({ codeName: "insertSpaces", default: false})
+  expandtab: boolean;
+
+  @overlapSetting({ codeName: "wordSepatators", default: "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?"})
```
Comment (jpoon) [inline src/configuration/configuration.ts]: Spelling. `wordSeparators`

File: src/cmd_line/commands/setoptions.ts [hunk 13]
```diff
@@ -0,0 +1,83 @@
...
+    this._name = 'setoptions';
+    this._shortName = 'option';
+    this._arguments = args;
+  }
+
+  get arguments() : IOptionArgs {
+    return this._arguments;
+  }
+
+  async execute(): Promise<void> {
```
Comment (johnfn) [inline src/cmd_line/commands/setoptions.ts]: Do something like if (!this._arguments.name) { return; } (and probably throw an error as well) so you dont have to use ! below

File: src/mode/modeHandler.ts [hunk 14]
```diff
@@ -174,21 +167,39 @@ export class SearchState {
       this._matchesDocVersion = TextEditor.getDocumentVersion();
       this._matchRanges = [];
 
+      /* Decide whether the search is case sensitive.
+       * If ignorecase is false, the search is case sensitive.
+       * If ignorecase is true, the search should be case insenstive.
```
Comment (jpoon) [inline src/mode/modeHandler.ts]: Spelling: case `insensitive`

File: src/mode/modeHandler.ts [hunk 15]
```diff
@@ -174,21 +167,39 @@ export class SearchState {
...
+       * If both ignorecase and smartcase are true, the search is case sensitive only when the search string contains UpperCase character.
+       */
+      let ignorecase = Configuration.getInstance().ignorecase;
+
+      if (ignorecase && Configuration.getInstance().smartcase && /[A-Z]/.test(search)) {
```
Comment (jpoon) [inline src/mode/modeHandler.ts]: Is this logic necessary?

**Comment by johnfn** [comment]
Instead of the object being a singleton, is it possible to export an instance of the class (rather than the class itself) and then use that directly?

I'm not actually sure if this is possible, but if it is it would improve the code a little. :-)

File: src/cmd_line/commands/setoptions.ts [hunk 16]
```diff
@@ -0,0 +1,83 @@
...
+    switch (this._arguments.operator) {
+      case SetOptionOperator.Set:
+        Configuration.getInstance()[this._arguments.name!] = true;
```
Comment (jpoon) [inline src/cmd_line/commands/setoptions.ts]: What does the `!` at the end mean?

File: src/mode/modeHandler.ts [hunk 17]
```diff
@@ -174,21 +167,39 @@ export class SearchState {
...
+        ignorecase = false;
+      }
+
+      const regex = new RegExp(search.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&"), ignorecase ? 'gi' : 'g');
```
Comment (johnfn) [inline src/mode/modeHandler.ts]: What is this regex? If we'll ever use it again, could you pull it into a constant somewhere? In either case, could you give it a better name?

**Comment by jpoon** [comment]
@rebornix Sweeeet. I added a couple of minor comments but LGTM!

File: src/mode/modeHandler.ts [hunk 18]
```diff
@@ -174,21 +167,39 @@ export class SearchState {
...
-        for (; i !== -1; i = line.indexOf(search, i + search.length)) {
+        while (result) {
           if (this._matchRanges.length >= SearchState.MAX_SEARCH_RANGES) {
             break outer;
           }
 
-          this._matchRanges.push(new vscode.Range(
-            new Position(lineIdx, i),
-            new Position(lineIdx, i + search.length)
+          this.matchRanges.push(new vscode.Range(
```
Comment (johnfn) [inline src/mode/modeHandler.ts]: Holy smokes, this PR includes smartcase as well? Heck yeah!

File: src/cmd_line/commands/setoptions.ts (hunk 16 above)
Comment (johnfn) [inline src/cmd_line/commands/setoptions.ts]: It's a new feature related to nullable types in Typescript 2.0. 

this._arguments.name is an optional type - it's either a string or undefined. The ! converts the type to a string.

**Comment by johnfn** [comment]
This is great! I think we together (ok, mostly you!) have arrived at a really good design for settings that should be really pleasant to add to in the future. Fix my few minor complaints and we should be good to go here.

File: src/configuration/configuration.ts [hunk 19]
```diff
@@ -0,0 +1,84 @@
...
+    for (const option in this) {
+      const vimOptionValue = vimOptions[option];
+      if (vimOptionValue !== null && vimOptionValue !== undefined) {
+        this[option] = vimOptionValue;
+      }
+    }
+  }
+
+  public static getInstance(): Configuration {
+    if (Configuration._instance == null) {
```
Comment (jpoon) [inline src/configuration/configuration.ts]: If somebody updates their workspace config, being a singleton, will this class retain the old value?

Comment (johnfn) [inline src/configuration/configuration.ts]: I'm ok with a restart for settings change if you are.

Comment (johnfn) [inline src/configuration/configuration.ts]: (We could do hot reloading as a feature later on...)

**Comment by johnfn** [comment]
And please ping me if I don't respond to a finished PR for a day or two. It's a little hard for me to sort through the PRs to know which ones are done, and I definitely don't want to leave anything that is done hanging around. :)

File: src/configuration/configuration.ts (hunk 19 above)
Comment (jpoon) [inline src/configuration/configuration.ts]: I'm ok with it. Just need to document it.

Comment (johnfn) [inline src/configuration/configuration.ts]: Hm, what's the alternative?

Comment (jpoon) [inline src/configuration/configuration.ts]: Nevermind, we read use this A LOT in our code. The alternative I had in mind initially was to read the configs from the file every time.

File: src/cmd_line/commands/setoptions.ts (hunk 16 above)
Comment (jpoon) [inline src/cmd_line/commands/setoptions.ts]: thanks

File: src/configuration/configuration.ts (hunk 9 above)
Comment (rebornix) [inline src/configuration/configuration.ts]: I'd love to `for of` if possible but `for of` is specific to collections, which requires the object has a [Symbol.iterator] property. So I just kept using `for in` to avoid making it complex.

File: src/mode/modeHandler.ts (hunk 15 above)
Comment (rebornix) [inline src/mode/modeHandler.ts]: It's how smart case works. Whether we should use `i` is decided by user's `ignorecase`, `smartcase` configuration and the search keyword.

**Comment by rebornix** [comment]
Update per comments and resolve conflicts.

**Comment by jpoon** [comment]
ship it.

File: src/mode/modeHandler.ts [hunk 20]
```diff
@@ -145,6 +146,7 @@ export class VimState {
    * by us or by a mouse action.
    */
   public whatILastSetTheSelectionTo: vscode.Selection;
+<<<<<<< b9a0b15742532ecc54e66ee04c417d82e70d29dc
```
Comment (johnfn) [inline src/mode/modeHandler.ts]: Wait, there are merge conflicts here.

File: src/mode/modeHandler.ts [hunk 21]
```diff
@@ -556,6 +577,7 @@ export class ModeHandler implements vscode.Disposable {
     });
   }
 
+<<<<<<< b9a0b15742532ecc54e66ee04c417d82e70d29dc
```
Comment (johnfn) [inline src/mode/modeHandler.ts]: More conflicts

File: src/mode/modeHandler.ts (hunk 20 above)
Comment (rebornix) [inline src/mode/modeHandler.ts]: I start to doubt myself as it happens several times. I remember correctly yesterday that I did remove these lines by `dd` and save them then use `git add . & git rebase --continue`. After that, I even search `====` globally as I made this kind of mistakes before, but damn, it still happens.

I'll try to track this down next time I do rebasing. The only potential catch came to my mind now is I always reload the window as jsdiff is hanging, I don't if this leads to the unsuccessful saving.

Comment (johnfn) [inline src/mode/modeHandler.ts]: Be careful, you want to use `git add . && git rebase --continue`. Using a single & will cause a process to be backgrounded. 

But yeah, it's annoying and it eventually happens to everyone. No worries :)

**Comment by moopie** [comment]
Any update on the .vimrc loading feature?
